# Generated by Django 4.1.7 on 2023-03-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ('id', 'timestamp')},
        ),
        migrations.AlterField(
            model_name='queue',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
