# Generated by Django 4.1.7 on 2023-05-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
